type ImageGroup = {
  images: string[];
};

type GroupedImages = {
  [key: number]: ImageGroup;
};

const groupedImages: GroupedImages = {
  0: {
    images: [
      "/conference/conference1.JPG",
      "/conference/conference2.JPG",
      "/conference/conference3.JPG",
      "/conference/conference4.JPG",
      "/conference/conference5.JPG",
      "/conference/conference6.JPG",
      "/conference/conference7.jpg",
      "/conference/conference8.jpg",
      "/conference/conference9.jpg",
      "/conference/conference10.jpg",
      "/conference/conference11.jpg",
      "/conference/conference12.JPG",
      "/conference/conference13.JPG",
      "/conference/conference14.JPG",
      "/conference/conference15.JPG",
      "/conference/conference16.JPG",
      "/conference/conference17.JPG",
      "/conference/conference18.JPG",
      "/conference/conference19.JPG",
      "/conference/conference20.JPG",
      "/conference/conference21.JPG",
      "/conference/conference22.JPG",
      "/conference/conference23.JPG",
      "/conference/conference24.JPG",
      "/conference/conference25.JPG",
      "/conference/conference26.jpg",
      "/conference/conference27.jpg",
      "/conference/conference28.jpg",
      "/conference/conference29.jpg",
      "/conference/conference30.jpg",
      "/conference/conference31.jpg",
      "/conference/conference32.jpg",
      "/conference/conference33.JPG",
      "/conference/conference34.JPG",
      "/conference/conference35.JPG",
      "/conference/conference36.JPG",
      "/conference/conference37.JPG",
      "/conference/conference39.jpg",
      "/conference/conference40.jpg",
      "/conference/conference41.jpg",
      "/conference/conference42.jpg",
      "/conference/conference43.jpg",
      "/conference/conference44.JPG",
      "/conference/conference45.jpg",
      "/conference/conference46.JPG",
      "/conference/conference47.JPG",
      "/conference/conference48.jpg",
      "/conference/conference49.jpg",
      "/conference/conference50.jpg",
      "/conference/conference51.jpg",
      "/conference/conference52.jpg",
      "/conference/conference53.JPG",
      "/conference/conference54.JPG",
      "/conference/conference55.JPG",
      "/conference/conference56.JPG",
      "/conference/conference57.JPG",
      "/conference/conference58.JPG",
      "/conference/conference59.jpg",
      "/conference/conference60.jpg",
      "/conference/conference61.jpg",
      "/conference/conference62.JPG",
    ],
  },
  1: {
    images: [
      "/promotion/promotion1.JPG",
      "/promotion/promotion2.JPG",
      "/promotion/promotion3.jpg",
      "/promotion/promotion4.jpg",
      "/promotion/promotion5.JPG",
      "/promotion/promotion6.jpg",
      "/promotion/promotion7.jpg",
      "/promotion/promotion8.jpg",
      "/promotion/promotion9.jpg",
      "/promotion/promotion10.jpg",
      "/promotion/promotion11.jpg",
      "/promotion/promotion12.jpg",
      "/promotion/promotion13.jpg",
      "/promotion/promotion14.jpg",
      "/promotion/promotion15.jpg",
      "/promotion/promotion16.jpg",
      "/promotion/promotion17.jpg",
      "/promotion/promotion18.jpg",
      "/promotion/promotion19.jpg",
      "/promotion/promotion20.jpg",
      "/promotion/promotion21.jpg",
      "/promotion/promotion22.jpg",
      "/promotion/promotion23.jpg",
      "/promotion/promotion24.jpg",
    ],
  },
  2: {
    images: [
      "/offline/offline1.JPG",
      "/offline/offline2.JPG",
      "/offline/offline3.JPG",
      "/offline/offline4.JPG",
      "/offline/offline5.jpg",
      "/offline/offline6.jpg",
      "/offline/offline7.jpg",
      "/offline/offline8.jpg",
      "/offline/offline9.jpg",
      "/offline/offline10.jpg",
      "/offline/offline11.jpg",
      "/offline/offline12.JPG",
      "/offline/offline13.JPG",
      "/offline/offline14.JPG",
      "/offline/offline15.JPG",
      "/offline/offline16.JPG",
      "/offline/offline17.jpg",
      "/offline/offline18.jpg",
      "/offline/offline19.jpg",
      "/offline/offline20.jpg",
      "/offline/offline21.jpg",
      "/offline/offline22.jpg",
      "/offline/offline23.jpg",
      "/offline/offline24.jpg",
      "/offline/offline25.jpg",
      "/offline/offline26.JPG",
      "/offline/offline27.JPG",
      "/offline/offline28.JPG",
      "/offline/offline29.JPG",
    ],
  },
  3: {
    images: [
      "/online/online1.jpg",
      "/online/online2.jpg",
      "/online/online3.JPG",
      "/online/online4.JPG",
    ],
  },
  4: {
    images: [
      "/golf/golf1.jpg",
      "/golf/golf2.JPG",
      "/golf/golf3.jpg",
      "/golf/golf4.jpg",
      "/golf/golf5.jpg",
      "/golf/golf6.jpg",
      "/golf/golf7.jpg",
      "/golf/golf8.jpg",
      "/golf/golf9.jpg",
      "/golf/golf10.jpg",
      "/golf/golf11.jpg",
      "/golf/golf12.jpg",
      "/golf/golf13.jpg",
      "/golf/golf14.jpg",
    ],
  },
};

export default groupedImages;
